/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DArticulos;
import Datos.DEntradas;
import Metodos.Metodos;
import Puentes.PuenteArticulo;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author AlejandroSaenz
 */
public class Entrada extends javax.swing.JFrame {
      public TextAutoCompleter ac;
      Metodos Metodos=new Metodos();
    /**
     * Creates new form Entrada
     */
      String tipoDeUsuario;
    public Entrada() {
    }

    Entrada(String tipo) {
        initComponents();
        tipoDeUsuario = tipo;
        ac = Metodos.autocompletarNombre(txtbN);
        MostrarTablaEntradas(TablaEntradas);
        setLocationRelativeTo(null);
        setResizable(false);
        btnGuardar.setEnabled(false);
        controlDeUsuarios(tipo);
    }
     public LocalTime hora(){
     LocalTime hora= LocalTime.now();
        
        return hora;
 }
     public void MostrarTablaEntradas(JTable TablaEntradas){
     Metodos me=new Metodos();
     me.MostrarTablaEntradas(TablaEntradas);
     }
     public void buscarPorNombre(){

         String BusquedaTicket = Metodos.Buscar_Nombre(txtbN.getText());
        if (BusquedaTicket.equals("Id no existe")) {JOptionPane.showMessageDialog(null, "Producto no existe"); txtbN.setText("");}
        else{
     
     
      
       //Aqui buscamos en la tabla articulo     
      DArticulos prov = new DArticulos();
      prov.setNombre(this.txtbN.getText());
      (new PuenteArticulo()).PuenteBuscarDatosArticulo2Nombre(prov);
      
      //Aqui llenamos los campos en el formulario
       txtBuscar.setText("" + prov.getId());
        txtNombre.setText("" + prov.getNombre());
        txtDescripcion.setText("" + prov.getDescripcion());
        txtStockActual.setText("" + prov.getStock());
        Categoria.setText("" + prov.getCategoria());
        txtCostoPromedio.setText(""+prov.getCosto_Promedio_U());
        //Calcular costo promedio unitario
       
        
      

        txtStockActual.setEnabled(false);
        btnGuardar.setEnabled(true);
        }
                

}
     
public void buscar(){
String BusquedaTicket = Metodos.Buscar_Id(txtBuscar.getText());
        if (BusquedaTicket.equals("Id no existe")) {JOptionPane.showMessageDialog(null, "Producto no existe"); txtBuscar.setText(""); }
        else{
        
       //Aqui buscamos en la tabla articulo     
      DArticulos prov = new DArticulos();
      prov.setId(Integer.parseInt(this.txtBuscar.getText()));
      (new PuenteArticulo()).PuenteBuscarDatosArticulo2(prov);
      
      //Aqui llenamos los campos en el formulario
//        txtId2.setText("" + prov.getId());
        txtNombre.setText("" + prov.getNombre());
        txtDescripcion.setText("" + prov.getDescripcion());
        txtStockActual.setText("" + prov.getStock());
        Categoria.setText("" + prov.getCategoria());
        txtCostoPromedio.setText(""+prov.getCosto_Promedio_U());
        //Calcular costo promedio unitario
       
        
      

        txtStockActual.setEnabled(false);
        btnGuardar.setEnabled(true);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEntradas = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCostoEntrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FechaEntrada = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtStockActual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Categoria = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCostoPromedio = new javax.swing.JTextField();
        txtbN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaEntradas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 650, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/10.png"))); // NOI18N
        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 120, 40));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 70, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/12.png"))); // NOI18N
        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 10, 120, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 370, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costo de Entrada:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        txtCostoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoEntradaActionPerformed(evt);
            }
        });
        txtCostoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoEntradaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCostoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel1.add(FechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 270, 120, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Stock Actual:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        txtStockActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActualActionPerformed(evt);
            }
        });
        txtStockActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockActualKeyTyped(evt);
            }
        });
        jPanel1.add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 107, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 120, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PrecioPromedioU");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        txtCostoPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoPromedioActionPerformed(evt);
            }
        });
        txtCostoPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoPromedioKeyTyped(evt);
            }
        });
        jPanel1.add(txtCostoPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 120, -1));

        txtbN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbNActionPerformed(evt);
            }
        });
        txtbN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbNKeyTyped(evt);
            }
        });
        jPanel1.add(txtbN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 620));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(txtBuscar.getText().length()>=5){

            txtBuscar.setText(txtBuscar.getText().substring(0,5));
            buscar();
        txtCantidad.requestFocus();}        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9')
        evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        buscar();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Marticulos m=new Marticulos(tipoDeUsuario);
        m.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCostoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoEntradaKeyTyped
        char car = evt.getKeyChar();
        if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
        evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoEntradaKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char car = evt.getKeyChar();
        if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
        evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased

    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void txtStockActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockActualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActualKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//CALCULAR PRECIO PROMEDIO U
float cantidadvieja,costopromedioviejo,cantidadnueva,costoentrada,costopromediounitario;
cantidadvieja=Float.parseFloat(txtStockActual.getText());
costopromedioviejo=Float.parseFloat(txtCostoPromedio.getText());
cantidadnueva=Float.parseFloat(txtCantidad.getText());
costoentrada=Float.parseFloat(txtCostoEntrada.getText());
costopromediounitario=((cantidadvieja*costopromedioviejo)+(cantidadnueva*costoentrada))/(cantidadnueva+cantidadvieja);
        System.out.println(costopromediounitario);
        
        Metodos Me=new Metodos();
     
        //Aqui Registramos la entrada en la tabla bitacora

        DEntradas En = new DEntradas();
       // En.setId(Integer.parseInt(txtId2.getText()));
        En.setNombre(txtNombre.getText());
        En.setDescripcion(txtDescripcion.getText());
        En.setCosto_Entrada(Float.parseFloat(txtCostoEntrada.getText()));
        En.setStock(Float.parseFloat(txtStockActual.getText()));
        En.setEntrada(Float.parseFloat(txtCantidad.getText()));
        Date fechaEntrada = FechaEntrada.getDate();
        long d = fechaEntrada.getTime();
        java.sql.Date soloFecha = new java.sql.Date(d);
        En.setFecha_Ultima_Entrada(soloFecha);
        En.setHora(hora().toString());
        En.setEstado("Entrada");
    
        En.setCategoria(Categoria.getText());
        

         
         
//Aqui agregamos las entradas al stock en la tabla articulos
      
        
        float StockActual = 0, Entrada = 0, Suma = 0;
        StockActual = (Float.parseFloat(txtStockActual.getText()));
        Entrada = (Float.parseFloat(txtCantidad.getText()));
        Suma = StockActual + Entrada;
        
       


         Me.ModificarStockYPrecioU(Suma,costopromediounitario,txtBuscar);
         System.out.println("modifica el precio y stock");
Me.GuardarEntradas(En);
 MostrarTablaEntradas(TablaEntradas);
buscar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCostoPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoPromedioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoPromedioKeyTyped

    private void txtbNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbNActionPerformed
        buscarPorNombre();        // TODO add your handling code here:
    }//GEN-LAST:event_txtbNActionPerformed

    private void txtbNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbNKeyReleased

    }//GEN-LAST:event_txtbNKeyReleased

    private void txtbNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbNKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbNKeyTyped

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        txtNombre.requestFocus();
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        txtDescripcion.requestFocus();
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCostoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoEntradaActionPerformed
        txtCantidad.requestFocus();
    }//GEN-LAST:event_txtCostoEntradaActionPerformed

    private void txtStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActualActionPerformed
        txtCostoEntrada.requestFocus();
    }//GEN-LAST:event_txtStockActualActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        txtStockActual.requestFocus();
    }//GEN-LAST:event_CategoriaActionPerformed

    private void txtCostoPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoPromedioActionPerformed
        Categoria.requestFocus();
    }//GEN-LAST:event_txtCostoPromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Categoria;
    private com.toedter.calendar.JDateChooser FechaEntrada;
    private javax.swing.JTable TablaEntradas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCostoEntrada;
    private javax.swing.JTextField txtCostoPromedio;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStockActual;
    public javax.swing.JTextField txtbN;
    // End of variables declaration//GEN-END:variables

    private void controlDeUsuarios(String tipo) {
        if("Solicitante".equals(tipo)){
            jPanel1.setVisible(false);
        }
    }
}
