/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Metodos.Metodos;
import Puentes.PuenteArticulo;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import menu.menu;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeException;
import net.sourceforge.barbecue.BarcodeFactory;
import net.sourceforge.barbecue.BarcodeImageHandler;
import net.sourceforge.barbecue.output.OutputException;

/**
 *
 * @author del.sistemas_res
 */
public class Marticulos extends javax.swing.JFrame {

    /**
     * Creates new form Marticulos
     */
    int cont = 0;
    String tipo = "";

    public Marticulos() {

    }

    public Marticulos(String tipoDeUsuario) {
        initComponents();
         btnReporte.setVisible(false);
        tipo = tipoDeUsuario;
        if (verificarReorden()) {
            Metodos me = new Metodos();
            TablaArticulo = me.MostrarTablaEnReorden(TablaArticulo);
            btnProductosReorden.setSelected(true);
            btnTodosLosProductos.setSelected(false);
             btnReporte.setVisible(true);
        } else {
            MostrarTablaArticulo(TablaArticulo);
            btnProductosReorden.setSelected(false);
            btnTodosLosProductos.setSelected(true);
             btnReporte.setVisible(false);
        }

        setLocationRelativeTo(null);
        setResizable(false);

        comboCategoria.addItem("");

        controlDeUsuarios();
    }

    public boolean verificarReorden() {
        boolean reorden;
        Metodos me = new Metodos();
        TablaArticulo = me.MostrarTablaEnReorden(TablaArticulo);
        if (TablaArticulo.getRowCount() > 0) {
            JOptionPane.showMessageDialog(null, TablaArticulo.getRowCount() + " articulo(s) se encuentra(n) en punto de reorden");
            reorden = true;
        } else {
            reorden = false;
        }
        return reorden;
    }

    public void MostrarTablaArticulo(JTable TablaArticulo) {
        (new PuenteArticulo()).PuenteMostrarTabla(TablaArticulo);
    }

    void MostrarTabla() {
        (new PuenteArticulo()).PuenteMostrarTablaTotalStaff(TablaArticulo, txtBuscar);
    }

    public void Buscar() {
        Metodos articulo = new Metodos();
        articulo.Buscar(TablaArticulo, txtBuscar.getText(), comboCategoria.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulo = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        btnTodosLosProductos = new javax.swing.JRadioButton();
        btnProductosReorden = new javax.swing.JRadioButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaArticuloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TablaArticuloMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(TablaArticulo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 59, 690, 390));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/10.png"))); // NOI18N
        jButton5.setText("REGRESAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 465, 139, 32));

        jPanel6.setBackground(new java.awt.Color(0, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ ARTICULOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 380, 60));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/14.png"))); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 380, 110));

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15.png"))); // NOI18N
        jButton6.setText("ENTRADAS");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.png"))); // NOI18N
        jButton7.setText("SALIDAS");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(44, 44, 44)
                .addComponent(jButton7)
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 380, 110));

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        jButton4.setText("CATEGORIAS");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton4)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 337, 380, 150));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 410, 500));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel6.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 430, -1));

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nombre", "Descripcion", "Costo_Entrada", "Costo_Promedio_U", "Stock", "Entrada", "Fecha_Ultima_Entrada", "Salida", "Fecha_Ultima_Salida", "Punto_Reorden", "Precio" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });
        jPanel6.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 239, -1));

        buttonGroup1.add(btnTodosLosProductos);
        btnTodosLosProductos.setSelected(true);
        btnTodosLosProductos.setText("Todos los Productos");
        btnTodosLosProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosLosProductosActionPerformed(evt);
            }
        });
        jPanel6.add(btnTodosLosProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, -1));

        buttonGroup1.add(btnProductosReorden);
        btnProductosReorden.setText("Productos en Punto de Reorden");
        btnProductosReorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosReordenActionPerformed(evt);
            }
        });
        jPanel6.add(btnProductosReorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, -1, -1));

        btnReporte.setText("Reporte");
        jPanel6.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Agregar agregara = new Agregar(tipo);
        agregara.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Eliminar eliminara = new Eliminar(tipo);
        eliminara.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Modificar modificara = new Modificar(tipo);
        modificara.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void TablaArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaArticuloMouseClicked
        if (tipo.equals("Administrador") || tipo.equals("Almacenista")) {
            Modificar mo = new Modificar(tipo);
            if (evt.getButton() == 1) {
                int fila = TablaArticulo.getSelectedRow();
                mo.txtId.setText(TablaArticulo.getValueAt(fila, 0).toString());
                mo.txtId2.setText(TablaArticulo.getValueAt(fila, 0).toString());
                mo.txtNombre.setText(TablaArticulo.getValueAt(fila, 1).toString());
                mo.txtDescripcion.setText(TablaArticulo.getValueAt(fila, 2).toString());
                mo.txtCostoEntrada.setText(TablaArticulo.getValueAt(fila, 3).toString());

                mo.txtStock.setText(TablaArticulo.getValueAt(fila, 5).toString());

                //tomar fecha del valor de la tabla y ponerla en ell jdatechooser
                String fe = TablaArticulo.getValueAt(fila, 7).toString();
                DateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                try {
                    Date fecha = formato.parse(fe);
                    mo.FechaEntrada.setDate(fecha);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error" + e);
                }
                mo.Categoria.setSelectedItem(TablaArticulo.getValueAt(fila, 8).toString());
                mo.txtReorden.setText(TablaArticulo.getValueAt(fila, 9).toString());
                mo.btne.setEnabled(true);
                mo.btnm.setEnabled(true);
                String x = TablaArticulo.getValueAt(fila, 10).toString();

                try {
                    final Barcode barcode = BarcodeFactory.createCode128(mo.txtId2.getText());
                    barcode.setBarHeight(60);
                    barcode.setBarWidth(2);
                    mo.lbBarcode.setIcon(new ImageIcon(BarcodeImageHandler.getImage(barcode)));
                } catch (BarcodeException ex) {
                    Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (OutputException ex) {
                    Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (x.equals("Inactivo")) {
                    mo.btne.setEnabled(false);
                    mo.btnm.setEnabled(false);
                    mo.btnActivar.setVisible(true);
                }

                mo.setVisible(true);
                dispose();
            }
        }

    }//GEN-LAST:event_TablaArticuloMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        menu me = new menu(tipo);
        me.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        Buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        Buscar();
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Cat ca = new Cat(tipo);
        ca.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Entrada e = new Entrada(tipo);
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Salida s = new Salida(tipo);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnProductosReordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosReordenActionPerformed
        if (btnProductosReorden.isSelected()) {
            Metodos me = new Metodos();
            TablaArticulo = me.MostrarTablaEnReorden(TablaArticulo);
            btnReporte.setVisible(true);
        }
    }//GEN-LAST:event_btnProductosReordenActionPerformed

    private void btnTodosLosProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosLosProductosActionPerformed
        if (btnTodosLosProductos.isSelected()) {
            MostrarTablaArticulo(TablaArticulo);
             btnReporte.setVisible(false);
        }
    }//GEN-LAST:event_btnTodosLosProductosActionPerformed

    private void TablaArticuloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaArticuloMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaArticuloMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaArticulo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JRadioButton btnProductosReorden;
    public javax.swing.JButton btnReporte;
    private javax.swing.JRadioButton btnTodosLosProductos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void controlDeUsuarios() {
        if ("Solicitante".equals(tipo)) {
            btnAgregar.setVisible(false);
            btnModificar.setVisible(false);
            jButton2.setVisible(false);
        }
    }
}
