/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import Controlador.ControladorExcel;
import Modelo.ModeloExcel;
import Presentacion.Bitacora;
import Presentacion.Catalogos;
import Presentacion.Marticulos;
import Presentacion.IFisico;
import Presentacion.alta_usuarios;
import Presentacion.login;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author del.sistemas_res
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    String tipoDeUsuario = "";
    public menu() {
        
    }

    public menu(String tipo) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        JLFecha.setText(Fecha());
        tipoDeUsuario = tipo;
        
        controlDeUsuarios();
        
    }

    public String Fecha() {
        Date Fecha = new Date() {
        };
        SimpleDateFormat FormatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return FormatoFecha.format(Fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        btnFisico = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnArticulos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnCatalogo = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnBitacora = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        JLFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFisico.setBackground(new java.awt.Color(255, 255, 255));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/18.png"))); // NOI18N
        jButton8.setText("I. FISICO");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnFisicoLayout = new javax.swing.GroupLayout(btnFisico);
        btnFisico.setLayout(btnFisicoLayout);
        btnFisicoLayout.setHorizontalGroup(
            btnFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFisicoLayout.setVerticalGroup(
            btnFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFisicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(btnFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 150, 150));

        btnAñadir.setText("Añadir Usuario");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel9.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 110, 30));

        btnArticulos.setBackground(new java.awt.Color(255, 255, 255));
        btnArticulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        jButton1.setText("ARTICULOS");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        btnArticulos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        jPanel9.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 150));

        btnCatalogo.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        jButton2.setText("CATALAGO");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnCatalogoLayout = new javax.swing.GroupLayout(btnCatalogo);
        btnCatalogo.setLayout(btnCatalogoLayout);
        btnCatalogoLayout.setHorizontalGroup(
            btnCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCatalogoLayout.setVerticalGroup(
            btnCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCatalogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel9.add(btnCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        btnBitacora.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/17.png"))); // NOI18N
        jButton3.setText("BITACORA");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnBitacoraLayout = new javax.swing.GroupLayout(btnBitacora);
        btnBitacora.setLayout(btnBitacoraLayout);
        btnBitacoraLayout.setHorizontalGroup(
            btnBitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBitacoraLayout.setVerticalGroup(
            btnBitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(btnBitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 150));

        jButton4.setText("Cerrar Sesión");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itDelicias.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 300, -1));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE INVENTARIOS");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 64));

        jLabel6.setText("FECHA");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 100, 20));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3.png"))); // NOI18N
        jButton7.setText("SALIR");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 140, 50));
        jPanel9.add(JLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 100, 20));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controlDeUsuarios(){
        //ADMIN
        btnAñadir.setVisible(false);
        if("Administrador".equals(tipoDeUsuario)){
            btnAñadir.setVisible(true);
        }
        //SOLICITANTE
        if("Solicitante".equals(tipoDeUsuario)){
            btnFisico.setVisible(false);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ModeloExcel modeloE = new ModeloExcel();
        IFisico vistaE = new IFisico(tipoDeUsuario);
        Marticulos VistaM = new Marticulos(tipoDeUsuario);
        ControladorExcel contraControladorExcel = new ControladorExcel(vistaE, modeloE,VistaM);
        VistaM.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Catalogos cat = new Catalogos(tipoDeUsuario);
        cat.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Bitacora bit = new Bitacora(tipoDeUsuario);
        bit.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ModeloExcel modeloE = new ModeloExcel();
        IFisico vistaE = new IFisico(tipoDeUsuario);
        Marticulos VistaM = new Marticulos(tipoDeUsuario);
        ControladorExcel contraControladorExcel = new ControladorExcel(vistaE, modeloE,VistaM);
        vistaE.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        alta_usuarios ventana = new alta_usuarios(tipoDeUsuario);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        login cerrar = new login();
        cerrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLFecha;
    private javax.swing.JPanel btnArticulos;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JPanel btnBitacora;
    private javax.swing.JPanel btnCatalogo;
    private javax.swing.JPanel btnFisico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
